# 2.1 Getting Data

In [3]:
import pandas as pd
import numpy as np

In [1]:
data = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv'
!wget $data   # this line of code simply fetches the file and downloads the file to current directory
                # useful when we want the data locally

--2026-09-23 14:39:51--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.110.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1.4M) [text/plain]
Saving to: ‘data.csv’

data.csv            100%[===================>]   1.41M  --.-KB/s    in 0.1s

2026-09-23 14:39:52 (13.7 MB/s) - ‘data.csv’ saved [1475504/1475504]

# 2.2 Data Preparation

In [20]:
df = pd.read_csv(data)

In [13]:
df.columns = df.columns.str.lower().str.replace(' ', '_' )  # only if we assign the changes to the df.columns then the original data frame and its contents get changed

,make,model,year,engine_fuel_type,engine_hp,engine_cylinders,transmission_type,driven_wheels,number_of_doors,market_category,vehicle_size,vehicle_style,highway_mpg,city_mpg,popularity,msrp
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

In [21]:
df.dtypes[df.dtypes =="str"]

Make                 str
Model                str
Engine Fuel Type     str
Transmission Type    str
Driven_Wheels        str
Market Category      str
Vehicle Size         str
Vehicle Style        str
dtype: object

In [26]:
strings = list(df.dtypes[df.dtypes == "str"].index)   # taking the columns which types are string and storing them in the list. Index means column names and values means their types.
strings

['Make',
 'Model',
 'Engine Fuel Type',
 'Transmission Type',
 'Driven_Wheels',
 'Market Category',
 'Vehicle Size',
 'Vehicle Style']

In [28]:
for col in strings:    # for converting every records/rows of columns of type string to small case and replacing spaces with _
    df[col] = df[col].str.lower().replace(' ', '_')

df.head(5)

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,bmw,1 series m,2011,premium unleaded (required),335.0,6.0,manual,rear wheel drive,2.0,"factory tuner,luxury,high-performance",compact,coupe,26,19,3916,46135
1,bmw,1 series,2011,premium unleaded (required),300.0,6.0,manual,rear wheel drive,2.0,"luxury,performance",compact,convertible,28,19,3916,40650
2,bmw,1 series,2011,premium unleaded (required),300.0,6.0,manual,rear wheel drive,2.0,"luxury,high-performance",compact,coupe,28,20,3916,36350
3,bmw,1 series,2011,premium unleaded (required),230.0,6.0,manual,rear wheel drive,2.0,"luxury,performance",compact,coupe,28,18,3916,29450
4,bmw,1 series,2011,premium unleaded (required),230.0,6.0,manual,rear wheel drive,2.0,luxury,compact,convertible,28,18,3916,34500

In [30]:
df.sample(5)  # used to look random rows of data rather than the same initial rows of data.

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
10724,ford,transit wagon,2017,regular unleaded,275.0,6.0,automatic,rear wheel drive,3.0,diesel,midsize,passenger van,19,14,5657,38015
1706,mazda,b-series pickup,1999,flex-fuel (unleaded/e85),150.0,6.0,manual,four wheel drive,2.0,flex fuel,compact,regular cab pickup,20,16,586,3011
1188,hyundai,accent,2016,regular unleaded,137.0,4.0,manual,front wheel drive,4.0,hatchback,compact,4dr hatchback,38,27,1439,14995
1464,chrysler,aspen,2008,regular unleaded,302.0,8.0,automatic,rear wheel drive,4.0,NaN,large,4dr suv,19,14,1013,32905
3169,chevrolet,cruze,2017,regular unleaded,153.0,4.0,automatic,front wheel drive,4.0,NaN,midsize,sedan,39,29,1385,23475

# 2.3 Exploratory Data Analysis (EDA)